name: todo_list
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.4
  hooks_riverpod: ^1.0.4
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  flutter_hooks: ^0.18.5+1
  injectable: ^1.5.3
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider_platform_interface: 2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^2.0.0
  injectable_generator: 1.5.4
  hive_generator: 1.1.3
  build_runner: 2.2.0

flutter: 
  uses-material-design: true
